export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const PAY_ORDER_SUCCESS = 'PAY_ORDER_SUCCESS';
export const PAY_ORDER_FAIL = 'PAY_ORDER_FAIL';
export const PAY_ORDER_RESET = 'PAY_ORDER_RESET';

export const MY_ORDERS_SUCCESS = 'MY_ORDERS_SUCCESS';
export const MY_ORDERS_FAIL = 'MY_ORDERS_FAIL';
export const MY_ORDERS_RESET = 'MY_ORDERS_RESET';

export const SELLER_ORDERS_SUCCESS = 'SELLER_ORDERS_SUCCESS';
export const SELLER_ORDERS_FAIL = 'SELLER_ORDERS_FAIL';
export const SELLER_ORDERS_RESET = 'SELLER_ORDERS_RESET';